{% set version = "0.7-6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-signal
  version: {{ version|replace("-", "_") }}

source:
  fn: signal_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/signal_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/signal/signal_{{ version }}.tar.gz
  sha256: 6b60277b07cf0167f8272059b128cc82f27a9bab1fd33d74c2a9e1f2abca5def

build:
  merge_build_host: true  # [win]
  number: 1006
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass

  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('signal')"  # [not win]
    - "\"%R%\" -e \"library('signal')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=signal
  license: GPL-2.0-only
  summary: A set of signal processing functions originally written for 'Matlab' and 'Octave'. Includes filter generation utilities, filtering functions, resampling routines, and visualization of filter models. It also includes interpolation functions.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
