{% set version = "1.8-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-signal
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/signal_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/signal/signal_{{ version }}.tar.gz
  sha256: 89cba854167a2b051a58cf3b73ccbf74eeb47c890ac39720611cd41f86b94684

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('signal')"           # [not win]
    - "\"%R%\" -e \"library('signal')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=signal
  license: GPL-2.0-only
  summary: A set of signal processing functions originally written for 'Matlab' and 'Octave'. Includes filter generation utilities, filtering functions, resampling routines, and visualization of filter models. It also includes interpolation functions.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: signal
# Title: Signal Processing
# Version: 0.7-7
# Date: 2021-05-24
# Authors@R: c(person("Uwe", "Ligges", role = c("aut", "cre"), email="ligges@statistik.tu-dortmund.de", comment = "new maintainer"), person("Tom", "Short", role = "aut", email = "tshort@eprisolutions.com", comment="port to R"), person("Paul", "Kienzle", role = "aut", comment="majority of the original sources"), person("Sarah", "Schnackenberg", role = "ctb", comment="various test cases and bug fixes"), person("David", "Billinghurst", role = "ctb"), person("Hans-Werner", "Borchers", role = "ctb"), person("Andre", "Carezia", role = "ctb"), person("Pascal", "Dupuis", role = "ctb"), person("John W.", "Eaton", role = "ctb"), person("E.", "Farhi", role = "ctb"), person("Kai", "Habel", role = "ctb"), person("Kurt", "Hornik", role = "ctb"), person("Sebastian", "Krey", role = "ctb"), person("Bill", "Lash", role = "ctb"), person("Friedrich", "Leisch", role = "ctb"), person("Olaf", "Mersmann", role = "ctb"), person("Paulo", "Neis", role = "ctb"), person("Jaakko", "Ruohio", role = "ctb"), person("Julius O.", "Smith III", role = "ctb"), person("Doug", "Stewart", role = "ctb"), person("Andreas", "Weingessel", role = "ctb"))
# Depends: R (>= 3.5.0)
# Imports: MASS, graphics, grDevices, stats, utils
# Suggests: pracma
# Enhances: matlab
# Description: A set of signal processing functions originally written for 'Matlab' and 'Octave'. Includes filter generation utilities, filtering functions, resampling routines, and visualization of filter models. It also includes interpolation functions.
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2021-05-24 23:53:43 UTC; ligges
# Author: Uwe Ligges [aut, cre] (new maintainer), Tom Short [aut] (port to R), Paul Kienzle [aut] (majority of the original sources), Sarah Schnackenberg [ctb] (various test cases and bug fixes), David Billinghurst [ctb], Hans-Werner Borchers [ctb], Andre Carezia [ctb], Pascal Dupuis [ctb], John W. Eaton [ctb], E. Farhi [ctb], Kai Habel [ctb], Kurt Hornik [ctb], Sebastian Krey [ctb], Bill Lash [ctb], Friedrich Leisch [ctb], Olaf Mersmann [ctb], Paulo Neis [ctb], Jaakko Ruohio [ctb], Julius O. Smith III [ctb], Doug Stewart [ctb], Andreas Weingessel [ctb]
# Maintainer: Uwe Ligges <ligges@statistik.tu-dortmund.de>
# Repository: CRAN
# Date/Publication: 2021-05-25 04:40:02 UTC
