appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MCTpLW9g405WGAyq8H/UTrL4AD+ZZr7SSLLXcEEHgzMGtnT82kNSkRIJ7Bp92WqRUGdADmtZ6u/rOOemIl3zIwnj5H+ouX2mBLc7dysKdLB6bfJ+eXKeO7hPZH8vq1G320FiSmcvg7Kve3tkzCirm8QNE+fDws4S//Nq9y+2jcd5pquioL9r2pU07sWt01q0yOm+1lDneIFV4OA8eIrFZIZQ69kXq05mmHdZ0ZNcAkHPtNu8UX1lHAZUcmSY6ZctyUMSD4awPS9rkXr4isvEvE+5rZt+fsP6lP+ta8EpPlLshEz3JtsIgQck/mDD1mUt3oZqe+braKLUct4pw0Lc4qA03PUJXlImou+ar7znpuIa5+gMeeSwVDuwzHqWCYobJwTpVp/ppKj82J016ZuIvFZ4mvuVFR7eoUeAjn35V0IIpAhk671u6yKNjdoP3iUQjZN03agTm42pdNHH/LX5mOTMDzGD3X8DvlV7p6MYpvsfGdq2gCZazb39+P6WHz4FCo8Ba2MD++0TzFsu9VN0pQIu2/E2gemy7OkN8vhVvHVwFqCapW94gObBKRogRiQjdmLs+cOwtcuXY3IwgpO9SbQSJh/sxa++cgaczSspTjyg6hsccZ1VBBapUXNTA20LNK/4EsGbk6mlb64aLPY7KxeKGxCdSLz9FtCVGuokXvQ=}
